apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-fetch-cronjob
  namespace: minio
spec:
  schedule: "0 6 * * *"  # Menjalankan setiap hari pukul 06:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: data-fetch-container
            image: muliaichsan17/data-fetch:latest  # Image Docker yang dibangun dan di-push
            envFrom:
            - configMapRef:
                name: data-fetch-config  # Referensi ke ConfigMap untuk environment variables
          restartPolicy: OnFailure
