apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "my-chart.fullname" . }}-cronjob
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: data-fetch-container
            image: "{{ .Values.cronjob.image }}"
            env:
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "my-chart.fullname" . }}-config
                  key: MINIO_ENDPOINT
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "my-chart.fullname" . }}-config
                  key: MINIO_BUCKET
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "my-chart.fullname" . }}-credentials
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "my-chart.fullname" . }}-credentials
                  key: MINIO_SECRET_KEY
          restartPolicy: OnFailure
