apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-chart.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ .Values.minio.accessKey | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.secretKey | b64enc | quote }}
