apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: keycloak
  namespace: dev-keycloak
spec:
  destination:
    name: keycloak
  sources:
    - name: authopia
      action: allow