---
apiVersion: v1
kind: Service
metadata:
  name: authopia-service
  labels:
    app: authopia
spec:
    selector:
        app: authopia
    ports:
     - protocol: TCP
       port: 3000
       targetPort: 3000