apiVersion: v1
kind: Service
metadata:
  name: authopia-service
  labels:
    app: app
spec:
    type: ClusterIP
    selector:
        app: app
    ports:
     - protocol: TCP
       port: 3000
       # targetPort: 3000
       # nodePort: 30080
