minio:
  endpoint: "https://minio.minio.svc.cluster.local:443"
  bucket: "stock-data-bucket"
  accessKey: ""
  secretKey: ""

cronjob:
  schedule: "*/5 * * * *"  # Menjalankan setiap hari pukul 06:00
  image: "muliaichsan17/data-fetch:latest"
