minio:
  endpoint: "http://minio-service.my-namespace.svc.cluster.local:9000"
  bucket: "stock-data-bucket"
  accessKey: ""
  secretKey: ""

cronjob:
  schedule: "0 6 * * *"  # Menjalankan setiap hari pukul 06:00
  image: "my-repo/data-fetch-job:latest"
