minio:
  endpoint: "https://minio.minio.svc.cluster.local:443"
  bucket: "stock-data-bucket"
  accessKey: ""  # This should be set to base64 encoded value
  secretKey: ""  # This should be set to base64 encoded value
  ticker_list: "ANTM.JK,BBRI.JK"  # Default ticker list
  start_date: "2021-01-01"  # Default start date

cronjob:
<<<<<<< Updated upstream
  schedule: "*/5 * * * *"  # Menjalankan setiap hari pukul 06:00
  image: muliaichsan17/data-fetch:c8417e6e685f93fc997fcd6635f75270dd1ce769
=======
  schedule: "*/2 * * * *"  # Menjalankan setiap hari pukul 06:00
  image: "muliaichsan17/data-fetch:latest"
>>>>>>> Stashed changes
